### ISSUE TITLE
classes lost when dragging

### ISSUE THREAD

**Issue by azz0r** [asbjornenge/react-drag-and-drop#10]
When an item is being dragged, are the original classNames dropped?

https://azz0r.github.io/wwe-draft-generator/

Take a look here how the bobbles lose their styling on drag

**Comment by asbjornenge** [comment]
@azz0r that is a briliant app you are making :grin: Had lots of fun dragging wrestlers around :tada: Anyway, this component does not render any special components during dragging, it simply uses the [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API). You might have to do some additional styling when dragging the images. It might be that you have some outer element og class hierarchy cutting the size of the element, which does not exists when dragging. Perhaps try styling the element directly? Or take a look at [this](http://www.kryogenix.org/code/browser/custom-drag-image.html) guide for examples of styling the dragged element directly.

I'll close this issue since it's not directly related to the component.

**Comment by azz0r** [comment]
Hey thanks for the response! Quick query that I wanted to avoid another issue on; It's running here  www.wwesim.com perfectly with one issue, users are reporting it drag and drop isn't working on mobile - does this module support it or would you have advice on a module I could use in tandeom with react-drag and drop?

**Comment by asbjornenge** [comment]
@azz0r seems the Drag and Drop API does not work on mobile http://caniuse.com/#feat=dragndrop Then this module will not either I'm afraid. Maybe [react-dnd](https://github.com/gaearon/react-dnd) supports mobile? I don't know.
